version: '3.3'

services:
  
  backend:
    container_name: app-web-page
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: spring-boot-web-thymeleaf-0.0.1-SNAPSHOT.jar
    restart: always
    ports:
      - 8080:8080
